kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-nfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["full-nfs-provisioner"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-full-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: full-nfs-provisioner
     # replace with namespace where provisioner is deployed
    namespace: full-nfs-provisioner
roleRef:
  kind: ClusterRole
  name: full-nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-full-nfs-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-full-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: full-nfs-provisioner
    # replace with namespace where provisioner is deployed
    namespace: full-nfs-provisioner
roleRef:
  kind: Role
  name: leader-locking-full-nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
