apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: image-policy
spec:
  repositories:
  - name: docker.io/gmoney23/nfs-client-provisioner:*
  - name: docker.io/gmoney23/busybox:1.31
