apiVersion: v1
kind: ServiceAccount
metadata:
  name: full-nfs-provisioner
imagePullSecrets: 
- name: sa-full-nfs-provisioner
---
kind: Service
apiVersion: v1
metadata:
  name: full-nfs-provisioner
  labels:
    app: full-nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: full-nfs-provisioner
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: full-nfs-provisioner
spec:
  selector:
    matchLabels:
      app: full-nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: full-nfs-provisioner
    spec:
      serviceAccount: full-nfs-provisioner
      nodeSelector:
         kubernetes.io/hostname: 9.56.28.25
      containers:
        - name: full-nfs-provisioner
          image: gmoney23/nfs-provisioner:latest
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=full-nfs-provisioner"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: full-nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /mnt/blockchain
